github.com:
    users:
        bhenrich:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: bhenrich
